### ISSUE TITLE
Compatibility with 4.2.6

### ISSUE THREAD

**Issue by iwr-redmond** [dunkeroni/InvokeAI_ModularDenoiseNodes#1]
Need to change a few imports:

ext_mask_guidance.py L31:
```
< from invokeai.app.invocations.latent import image_resized_to_grid_as_tensor, ImageToLatentsInvocation
---
> from invokeai.backend.stable_diffusion.diffusers_pipeline import image_resized_to_grid_as_tensor
> from invokeai.app.invocations.image_to_latents import ImageToLatentsInvocation

```

denoise_latents_nodes.py L15:

```
< from invokeai.app.invocations.constants import LATENT_SCALE_FACTOR, SCHEDULER_NAME_VALUES
---
> from invokeai.app.invocations.constants import LATENT_SCALE_FACTOR
> from invokeai.app.invocations.scheduler import SCHEDULER_NAME_VALUES

```

denoise_latents_nodes.py L55:

```
< from invokeai.app.invocations.latent import get_scheduler
---
> from invokeai.app.invocations.denoise_latents import get_scheduler
```
Further compatibility untested, FYI.

**Comment by dunkeroni** [comment]
I'm out of town and can't do much testing myself, but I'll see about getting a hotfix for the imports.

At the moment, there is ongoing work to rewrite the Invoke backend in a modular fashion to support these sorts of nodes natively. Once that happens all of this will be rewritten (again). Stay tuned :)
